// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiRH.Models;

namespace WebApiRH.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200526225954_addedNullable3")]
    partial class addedNullable3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiRH.Models.Advert", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("EditedAt");

                    b.Property<Guid>("Fk_Author");

                    b.Property<int>("Fk_Category");

                    b.Property<Guid?>("Fk_Image");

                    b.Property<Guid>("Fk_LocalGroup");

                    b.Property<bool>("Removed");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Uid");

                    b.HasIndex("Fk_Author");

                    b.HasIndex("Fk_Image");

                    b.HasIndex("Fk_LocalGroup");

                    b.ToTable("Advert");
                });

            modelBuilder.Entity("WebApiRH.Models.AdvertsReview", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("EditedAt");

                    b.Property<Guid>("Fk_Advert");

                    b.Property<Guid>("Fk_Author");

                    b.Property<bool>("Removed");

                    b.Property<string>("Reviews")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("Uid");

                    b.HasIndex("Fk_Advert");

                    b.HasIndex("Fk_Author");

                    b.ToTable("AdvertsReview");
                });

            modelBuilder.Entity("WebApiRH.Models.Answer", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<Guid>("Fk_Voting");

                    b.Property<string>("Option")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Uid");

                    b.HasIndex("Fk_Voting");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("WebApiRH.Models.ChatReply", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("EditedAt");

                    b.Property<Guid>("FK_Author");

                    b.Property<Guid>("Fk_GroupChat");

                    b.Property<Guid>("Fk_Image");

                    b.Property<bool>("Removed");

                    b.Property<string>("Reply")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("Uid");

                    b.HasIndex("FK_Author");

                    b.HasIndex("Fk_GroupChat");

                    b.HasIndex("Fk_Image");

                    b.ToTable("ChatReply");
                });

            modelBuilder.Entity("WebApiRH.Models.Dialogue", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("EditedAt");

                    b.Property<Guid>("FkUser1");

                    b.Property<Guid>("FkUser2");

                    b.Property<bool>("Removed");

                    b.HasKey("Uid");

                    b.HasIndex("FkUser1");

                    b.HasIndex("FkUser2");

                    b.ToTable("Dialogue");
                });

            modelBuilder.Entity("WebApiRH.Models.GroupChat", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("EditedAt");

                    b.Property<Guid>("Fk_Author");

                    b.Property<Guid?>("Fk_Image");

                    b.Property<Guid>("Fk_LocalGroup");

                    b.Property<bool>("Removed");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("Uid");

                    b.HasIndex("Fk_Author");

                    b.HasIndex("Fk_Image");

                    b.HasIndex("Fk_LocalGroup");

                    b.ToTable("GroupChat");
                });

            modelBuilder.Entity("WebApiRH.Models.Home", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Appartaments");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("EditedAt");

                    b.Property<Guid>("Fk_ImageUrl");

                    b.Property<Guid>("Fk_Manager");

                    b.Property<int>("Fk_Status");

                    b.Property<int>("Floors");

                    b.Property<string>("HomeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("Porches");

                    b.Property<bool>("Removed");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("YearCommissioning");

                    b.HasKey("Uid");

                    b.HasIndex("Fk_ImageUrl");

                    b.HasIndex("Fk_Manager");

                    b.ToTable("Home");
                });

            modelBuilder.Entity("WebApiRH.Models.Images", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Url")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UrlRemove");

                    b.HasKey("Uid");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("WebApiRH.Models.LocalGroup", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("EditedAt");

                    b.Property<Guid>("Fk_Home");

                    b.Property<Guid>("Fk_Image");

                    b.Property<int>("Fk_Status");

                    b.Property<Guid>("Fk_Supervisor");

                    b.Property<bool>("Removed");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Uid");

                    b.HasIndex("Fk_Home");

                    b.HasIndex("Fk_Image");

                    b.HasIndex("Fk_Supervisor");

                    b.ToTable("LocalGroup");
                });

            modelBuilder.Entity("WebApiRH.Models.Message", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("EditedAt");

                    b.Property<Guid>("Fk_Author");

                    b.Property<Guid>("Fk_Dialogue");

                    b.Property<Guid>("Fk_Image");

                    b.Property<bool>("Removed");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.HasKey("Uid");

                    b.HasIndex("Fk_Author");

                    b.HasIndex("Fk_Dialogue");

                    b.HasIndex("Fk_Image");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("WebApiRH.Models.Participant", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("Fk_LocalGroup");

                    b.Property<Guid>("Fk_User");

                    b.HasKey("Uid");

                    b.HasIndex("Fk_LocalGroup");

                    b.HasIndex("Fk_User");

                    b.ToTable("Participant");
                });

            modelBuilder.Entity("WebApiRH.Models.User", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasColumnType("Nvarchar(MAX)");

                    b.Property<int>("Appartament");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("EditedAt");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("Fk_Avatar");

                    b.Property<int?>("Fk_Gender");

                    b.Property<Guid?>("Fk_Home");

                    b.Property<int>("Fk_Role");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("Nvarchar(100)");

                    b.Property<bool>("IsApprovedHome");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(17)");

                    b.Property<bool>("Removed");

                    b.HasKey("Uid");

                    b.HasIndex("Fk_Avatar");

                    b.HasIndex("Fk_Home");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WebApiRH.Models.Voted", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateAt");

                    b.Property<Guid>("Fk_Answer");

                    b.Property<Guid>("Fk_User");

                    b.Property<Guid>("Fk_Voting");

                    b.HasKey("Uid");

                    b.HasIndex("Fk_Answer");

                    b.HasIndex("Fk_User");

                    b.HasIndex("Fk_Voting");

                    b.ToTable("Voted");
                });

            modelBuilder.Entity("WebApiRH.Models.Voting", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<DateTime>("EditedAt");

                    b.Property<Guid>("Fk_Advert");

                    b.Property<bool>("IsMulti");

                    b.Property<bool>("Removed");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TotalVotes");

                    b.Property<string>("YourOption")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Uid");

                    b.HasIndex("Fk_Advert");

                    b.ToTable("Voting");
                });

            modelBuilder.Entity("WebApiRH.Models.Advert", b =>
                {
                    b.HasOne("WebApiRH.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("Fk_Author")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApiRH.Models.Images", "Image")
                        .WithMany()
                        .HasForeignKey("Fk_Image");

                    b.HasOne("WebApiRH.Models.LocalGroup", "LocalGroup")
                        .WithMany("Adverts")
                        .HasForeignKey("Fk_LocalGroup")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApiRH.Models.AdvertsReview", b =>
                {
                    b.HasOne("WebApiRH.Models.Advert", "Advert")
                        .WithMany("Reviews")
                        .HasForeignKey("Fk_Advert")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApiRH.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("Fk_Author")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApiRH.Models.Answer", b =>
                {
                    b.HasOne("WebApiRH.Models.Voting", "Voting")
                        .WithMany("Options")
                        .HasForeignKey("Fk_Voting")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApiRH.Models.ChatReply", b =>
                {
                    b.HasOne("WebApiRH.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("FK_Author")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApiRH.Models.GroupChat", "GroupChat")
                        .WithMany("GroupReplys")
                        .HasForeignKey("Fk_GroupChat")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApiRH.Models.Images", "Image")
                        .WithMany()
                        .HasForeignKey("Fk_Image")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApiRH.Models.Dialogue", b =>
                {
                    b.HasOne("WebApiRH.Models.User", "Member1")
                        .WithMany()
                        .HasForeignKey("FkUser1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApiRH.Models.User", "Member2")
                        .WithMany()
                        .HasForeignKey("FkUser2")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApiRH.Models.GroupChat", b =>
                {
                    b.HasOne("WebApiRH.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("Fk_Author")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApiRH.Models.Images", "Image")
                        .WithMany()
                        .HasForeignKey("Fk_Image");

                    b.HasOne("WebApiRH.Models.LocalGroup", "LocalGroup")
                        .WithMany("Messages")
                        .HasForeignKey("Fk_LocalGroup")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApiRH.Models.Home", b =>
                {
                    b.HasOne("WebApiRH.Models.Images", "ImageUrl")
                        .WithMany()
                        .HasForeignKey("Fk_ImageUrl")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApiRH.Models.User", "Manager")
                        .WithMany()
                        .HasForeignKey("Fk_Manager")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApiRH.Models.LocalGroup", b =>
                {
                    b.HasOne("WebApiRH.Models.Home", "Home")
                        .WithMany("LocalGroups")
                        .HasForeignKey("Fk_Home")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApiRH.Models.Images", "Image")
                        .WithMany()
                        .HasForeignKey("Fk_Image")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApiRH.Models.User", "Supervisor")
                        .WithMany("ManagedGroups")
                        .HasForeignKey("Fk_Supervisor")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApiRH.Models.Message", b =>
                {
                    b.HasOne("WebApiRH.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("Fk_Author")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApiRH.Models.Dialogue", "Dialogue")
                        .WithMany("Messages")
                        .HasForeignKey("Fk_Dialogue")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApiRH.Models.Images", "Image")
                        .WithMany()
                        .HasForeignKey("Fk_Image")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApiRH.Models.Participant", b =>
                {
                    b.HasOne("WebApiRH.Models.LocalGroup", "LocalGroup")
                        .WithMany("Users")
                        .HasForeignKey("Fk_LocalGroup")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApiRH.Models.User", "User")
                        .WithMany("MyGroups")
                        .HasForeignKey("Fk_User")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApiRH.Models.User", b =>
                {
                    b.HasOne("WebApiRH.Models.Images", "Avatar")
                        .WithMany()
                        .HasForeignKey("Fk_Avatar")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApiRH.Models.Home", "Home")
                        .WithMany("Tenants")
                        .HasForeignKey("Fk_Home");
                });

            modelBuilder.Entity("WebApiRH.Models.Voted", b =>
                {
                    b.HasOne("WebApiRH.Models.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("Fk_Answer")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApiRH.Models.User", "User")
                        .WithMany("Voteds")
                        .HasForeignKey("Fk_User")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApiRH.Models.Voting", "Voting")
                        .WithMany("Voteds")
                        .HasForeignKey("Fk_Voting")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApiRH.Models.Voting", b =>
                {
                    b.HasOne("WebApiRH.Models.Advert", "Advert")
                        .WithMany("Votings")
                        .HasForeignKey("Fk_Advert")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
